FROM ruby:3.3.0-bookworm

ENV BUNDLE_PATH="/usr/local/bundle" \
    APP_PATH="/opt/puppix_api" \
    EDITOR="vim"

ARG USER_ID=0
ARG GROUP_ID=0

RUN addgroup --gid $GROUP_ID docker && \
    adduser --gid $GROUP_ID --uid $USER_ID --gecos '' --disabled-password docker

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y vim && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

RUN chown -R docker:docker /opt && \
    chown -R docker:docker /usr/local/bundle

USER $USER_ID

WORKDIR $APP_PATH

COPY ./bin/docker-entrypoint /usr/bin/

ENTRYPOINT ["/usr/bin/docker-entrypoint"]

EXPOSE 3000

CMD ["./bin/rails", "server", "-b", "0.0.0.0"]
